spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: resume-service
          uri: lb://RESUME-SERVICE
          predicates:
            - Path=/api/resumes/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/