spring:
  application:
    name: parser-service

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: parser-group
      auto-offset-reset: earliest

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/