spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/resumedb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: Asia/Kolkata

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/