spring:
  application:
    name: resume-service

  datasource:
    url: jdbc:postgresql://postgres:5432/resumedb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: Asia/Kolkata

  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/